### ISSUE TITLE
but what to put in conkyrc file ?

### ISSUE THREAD

**Issue by s4my** [fisadev/conky-draw#3]
this will all to well but this lacks a crucial part which is what to put on the conkyrc file to display let's say a simple ring with the cpu usage (let's say cpu0 and cpu1)?

**Comment by fisadev** [comment]
Sorry for the delay. I had a very busy week :)

The installation [instructions](https://github.com/fisadev/conky-draw#installation) in the README explain what to add to your conkyrc. You only need two lines to "launch" conky draw:

```
lua_load ./conky_draw.lua
lua_draw_hook_post main
```

Be sure of two things:
- your conky supports lua, otherwise it wont work
- your conky window has enough space for the things you are drawing, otherwise you won't see them

All the definitions of the graphs you want to show, goes then in the `conky_draw_config.lua` file (template in the repo). For the example of the cpus rings, it could be something like this:

```
elements = {
    {
        kind = 'ring_graph',
        conky_value = 'cpu cpu0',
        center = {x = 75, y = 100},
        radius = 30,
    },
    {
        kind = 'ring_graph',
        conky_value = 'cpu cpu0',
        center = {x = 75, y = 100},
        radius = 30,
    },
}
```

**Comment by s4my** [comment]
thank you so much that was very helpful :+1:
